### PR TITLE
Pin ansible-lint to 6.0.2

### LINKED ISSUE #1470: Pip Can't Find a Suitable Version of jsonschema Now That ansible-lint Depends On It
**Describe the bug**

[The build is broken](https://github.com/megalinter/megalinter/runs/6378047672?check_suite_focus=true#step:8:1636).

pip is unable to find a version of snakemake that is compatible with the other dependencies. It keeps trying older and older versions until it eventually reaches 5.27.2, a bad release that cannot be set up. The issue may be reproduced locally by running `pip install ansible-lint cfn-lint snakemake` (or `pip install ansible-lint cfn-lint`). The breakage is unrelated to this pull request. It was caused by [ansible/ansible-lint#2035](https://github.com/ansible/ansible-lint/pull/2035/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R35), which added a dependency on `jsonschema==4.5.1`, whereas [cfn-lint requires `jsonschema~=3.0`](https://github.com/aws-cloudformation/cfn-lint/blob/c381e5f9d0611d4959c317426dbbe248252a58f5/setup.py#L48). One short-term approach might be for us to pin `ansible-lint==6.0.2`. Longer term, it might be better to use [Poetry](https://python-poetry.org/) than pip since it would allow us to lock the transitive closure of our dependencies and automatically explain any conflicts caused by upgrades to us.

**To Reproduce**

1. Open a pull request against MegaLinter containing a trivial modification.

**Expected behavior**

I expected the build to pass.

**Additional context**
Discovered in #1469.

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
Fixes #1470.

ansible-lint 6.1.0 adds a dependency on `jsonschema==4.5.1`, which conflicts with cfn-lint's pre-existing dependency on `jsonschema~=3.0`. Also remove extras community and yamllint since they are no longer provided by ansible-lint.

## Proposed Changes

1. Pin ansible-lint to 6.02.
2. Remove ansible-lint's extras: community and yamllint.
3. Fix typo in bash-exec description.

This change breaks the auto-generated link to ansible-lint in its documentation, and confusingly shuffles the order of some of the documentation around. Such changes were made by `build.sh`.

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/2310145834)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|0.03s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|0.23s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|0.19s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.95s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |3.54s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.25s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.9s        |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.18s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|2.27s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|4.85s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   21|     |                                                                         0|14.97s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  255|    0|                                                                         0|4.77s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  255|     |                                                                         0|4.64s       |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  255|    0|                                                                         0|4.4s        |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.16s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  150|     |[**64**](https://github.com/megalinter/megalinter/actions/runs/2310145834)|1.93s       |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  150|    0|                                                                         0|2.71s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  150|     |                                                                         0|2.29s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  150|    0|                                                                         0|0.5s        |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  150|     |                                                                         0|102.81s     |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  150|     |                                                                         0|15.05s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  534|     |                                                                         0|14.73s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  378|    0|                                                                         0|0.48s       |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.01s       |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|2.67s       |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|23.59s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.26s       |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/megalinter/megalinter/actions/runs/2310145834)

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/2310145850)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|0.03s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|0.25s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|0.05s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.91s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |4.03s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.25s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.75s       |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.03s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|2.04s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|4.97s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   21|     |                                                                         0|14.5s       |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  255|    2|                                                                         0|4.63s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  255|     |                                                                         0|4.59s       |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  255|    2|                                                                         0|4.02s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.04s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  150|     |[**64**](https://github.com/megalinter/megalinter/actions/runs/2310145850)|1.88s       |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  150|    0|                                                                         0|3.21s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  150|     |                                                                         0|2.59s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  150|    0|                                                                         0|0.34s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  150|     |                                                                         0|103.18s     |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  150|     |                                                                         0|15.49s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  534|     |                                                                         0|14.64s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  378|    2|                                                                         0|0.35s       |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.01s       |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|2.65s       |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|25.33s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.35s       |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/megalinter/megalinter/actions/runs/2310145850)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [**megalinter/megalinter/flavors/python@v5**](https://megalinter.github.io/flavors/python/) (49 linters)

**Review by nvuillam — APPROVED** [review]
it seems that will do the job ,thanks :)

**Comment by Kurt-von-Laven** [comment]
Does using Poetry with a lock file so we can lock our transitive dependencies seem like a reasonable next step? If so, I am happy to take a stab at porting us off pip since I am reasonably comfortable with Poetry at this point.

**Comment by nvuillam** [comment]
I have never used poetry but if you feel confident, let's go :)
What will be the changes compare to pip ?

**Comment by Kurt-von-Laven** [comment]
Sorry I missed this message! Top-level dependencies can be pinned using, for example, a `requirements.txt` file in pip, but the only way I know of to pin transitive dependencies in pip is to add them as top-level dependencies. Even then, pip doesn't store checksums, so a package can be re-released at the same version with malicious code. Poetry uses a lock file to avoid these issues and offers a number of other features above and beyond pip's capabilities. It runs quickly in my experience. I will tackle this issue next since I think it's more pressing than some of the others in my queue. I plan to use asdf to install Poetry to get the ball rolling on simplifying our dependency management.

**Pull request merged**
