### PR TITLE
New linter: kubeconform

### LINKED ISSUE #1268: Support kubeconform
**Is your feature request related to a problem? Please describe.**

:wave: kubeval is mostly outdated and rarely updated, it would be neat to support kubeconform

https://github.com/yannh/kubeconform

### PR DESCRIPTION
**Pull request by Yann-J**
Fixes #1268

## Proposed Changes

1. Added new linter `kubeconform` to validate kubernetes manifests

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
@Yann-J great ! :)

To make CI pass, you should update `.automation/test/kubernetes/kubernetes/kubeval_bad_1.yaml` so that kubeconform fails on this file :)

**Comment by Yann-J** [comment]
Thanks @nvuillam - the bad file does fail but I've been struggling to find the right regex to properly parse the failure counts (the tool reports separate counts for 'invalid' and 'error' files)... I think I've got it now as I finally managed to build locally to experiment faster (my docker build had been failing till now due to github API quotas hit during the build).

Let's see how this CI run goes...

**Comment by nvuillam** [comment]
@Yann-J quick question: does ` kubeconform -v` not work ?
Usually we use linter_version_cache when the version is not available from the linter command line

Else, there are properties that can be overridden:
- cli_version_arg_name (default: `--version` )
- version_extract_regex (default: `\d+(\.\d+)+` )

**Comment by Yann-J** [comment]
Indeed, oddly, there's a `-v` argument documented in the github README... but it's not in any of the versions of the binary I've tried...

I'm not really sure what's going on now... For some reason I cannot find the tests in my VS Code (I can see some, but not the linter tests...). However, the docker image builds locally and seems to work quite fine with the kubernetes tests files.

I guess I don't fully understand how the test works, because in the CI logs I can see that the test is actually correctly failing on the `bad` file... which I guess should be expected... I can see that the file is failing validation, and megalinter is correctly reporting 1 failed file... so I don't fully understand why this is failing the CI test?

Here's the run log:

```
Kept [1] files on [4] found files
Kept files before applying linter filters:
- /tmp/lint/.automation/test/kubernetes/kubernetes/kubeval_bad_1.yaml
[Filters] {'name': 'KUBERNETES_KUBECONFORM', 'filter_regex_include': None, 'filter_regex_exclude': None, 'files_sub_directory': 'kubernetes', 'lint_all_files': False, 'lint_all_other_linters_files': False, 'file_extensions': ['.yml', '.yaml', '.json'], 'file_names_regex': [], 'file_names_not_ends_with': [], 'file_contains_regex': ['apiVersion:', 'kustomize\\.config\\.k8s\\.io', 'tekton']}
KUBERNETES_KUBECONFORM linter kept 1 files after applying linter filters:
- /tmp/lint/.automation/test/kubernetes/kubernetes/kubeval_bad_1.yaml

+----MATCHING LINTERS------+------------------+----------------+------------+
| Descriptor | Linter      | Criteria         | Matching files | Format/Fix |
+------------+-------------+------------------+----------------+------------+
| KUBERNETES | kubeconform | .yml|.yaml|.json | 1              | no         |
+------------+-------------+------------------+----------------+------------+

MegaLinter flavor is "all", no need to check match with linters
[kubeconform] command: ['kubeconform', '-summary', '-cache', '/tmp/', '/tmp/lint/.automation/test/kubernetes/kubernetes/kubeval_bad_1.yaml']
[kubeconform] CWD: /
[kubeconform] result: 1 /tmp/lint/.automation/test/kubernetes/kubernetes/kubeval_bad_1.yaml - ReplicationController bob is invalid: For field spec.replicas: Invalid type. Expected: [integer,null], given: string
Summary: 1 resource found in 1 file - Valid: 0, Invalid: 1, Errors: 0, Skipped: 0


### Processed [KUBERNETES] files
- Using [kubeconform v0.4.12] https://megalinter.github.io/23231bd23dc7ec959921027cf3b7e8c16c24c956/descriptors/kubernetes_kubeconform
- MegaLinter key: [KUBERNETES_KUBECONFORM]
- Rules config: identified by [kubeconform]
[kubeconform] .automation/test/kubernetes/kubernetes/kubeval_bad_1.yaml
--Error detail:
/tmp/lint/.automation/test/kubernetes/kubernetes/kubeval_bad_1.yaml - ReplicationController bob is invalid: For field spec.replicas: Invalid type. Expected: [integer,null], given: string
Summary: 1 resource found in 1 file - Valid: 0, Invalid: 1, Errors: 0, Skipped: 0

❌ Linted [KUBERNETES] files with [kubeconform]: Found 1 error(s) - (0.47s)
Skipped post of Github Status for KUBERNETES with kubeconform
[Text Reporter] Generated TEXT report: /tmp/90ec4dc6-2865-448a-916e-0e67d77fc2e1/linters_logs/ERROR-KUBERNETES_KUBECONFORM.log
[Post] No commands declared in user configuration

+----SUMMARY----+-------------+---------------+-------+-------+--------+--------------+
| Descriptor    | Linter      | Mode          | Files | Fixed | Errors | Elapsed time |
+---------------+-------------+---------------+-------+-------+--------+--------------+
| ❌ KUBERNETES | kubeconform | list_of_files |     1 |       |      1 |        0.47s |
+---------------+-------------+---------------+-------+-------+--------+--------------+
```

Any hints to guide me here?

**Comment by nvuillam** [comment]
@Yann-J the test class checks that the number is > 1 , so you could add errors in the test file so there are more than one detected with the regex :)

image

About tests in VsCode , you need those 2 extensions:
- https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer
- https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter

**Comment by Yann-J** [comment]
Oh, OK, I see that the failure is actually not from the linting failure, but from the parsing of the error count:

```
=================================== FAILURES ===================================
___________________ kubernetes_kubeconform_test.test_failure ___________________

self = <kubernetes_kubeconform_test.kubernetes_kubeconform_test testMethod=test_failure>

    def test_failure(self):
        utilstest.linter_test_setup()
>       utilstest.test_linter_failure(self.get_linter_instance(), self)

megalinter/tests/test_megalinter/LinterTestRoot.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
megalinter/tests/test_megalinter/helpers/utilstest.py:252: in test_linter_failure
    test_self.assertTrue(
E   AssertionError: False is not true : Unable to count number of errors from logs with count method regex_sum and regex (?:Invalid|Errors): ([0-9]+)
```

But I find this puzzling because this is working locally for me (and confirmed by a regex tester), and also seems to work in CI, judging from the run log which are correctly picking up the error...

**Comment by Yann-J** [comment]
Hmm, the count seems correct locally... The tool will only report 1 failure per file, but if I add another bad file, I can see it's summing things properly: out of 3 files, 1 is good, 2 are bad (1 invalid, 1 error [does not have a schema for this object]):

```
### Processed [KUBERNETES] files
- Using [kubeconform v0.4.12] https://megalinter.github.io//descriptors/kubernetes_kubeconform
- MegaLinter key: [KUBERNETES_KUBECONFORM]
- Rules config: identified by [kubeconform]
[kubeconform] kubernetes/kubeval_bad_1.yaml
[kubeconform] kubernetes/kubeval_bad_2.yaml
[kubeconform] kubernetes/kubeval_good_1.yaml
--Error detail:
/tmp/lint/kubernetes/kubeval_bad_2.yaml - UnknownKind bob failed validation: could not find schema for UnknownKind
/tmp/lint/kubernetes/kubeval_bad_1.yaml - ReplicationController bob is invalid: For field spec.replicas: Invalid type. Expected: [integer,null], given: string
Summary: 3 resources found in 3 files - Valid: 1, Invalid: 1, Errors: 1, Skipped: 0

❌ Linted [KUBERNETES] files with [kubeconform]: Found 2 error(s) - (2.31s)
[Text Reporter] Generated TEXT report: /tmp/lint/report/linters_logs/ERROR-KUBERNETES_KUBECONFORM.log

+----SUMMARY----+-------------+---------------+-------+-------+--------+--------------+
| Descriptor    | Linter      | Mode          | Files | Fixed | Errors | Elapsed time |
+---------------+-------------+---------------+-------+-------+--------+--------------+
| ❌ KUBERNETES | kubeconform | list_of_files |     3 |       |      2 |        2.31s |
+---------------+-------------+---------------+-------+-------+--------+--------------+
```

**Comment by nvuillam** [comment]
I don't understand why the CI didn't run...
Maybe you can add an empty space in the descriptor yml file ?
Job CI trigger is not on all files updates :/

**Comment by Yann-J** [comment]
OK, I get it now... indeed, an error count > 1 fixed the CI test.

Looks like we're good to go now @nvuillam , happy to get your review!

**Review by nvuillam — APPROVED** [review]
Great contribution, thanks :)

**Comment by nvuillam** [comment]
@Yann-J I rollbacked the LICENSE that you replaced with kubeconform one... but except that it is a great PR :)

**Pull request merged**
