### PR TITLE
Implementation of solidity linter, added the descriptor and the test …

### PR DESCRIPTION
**Pull request by leogalbu**
## Proposed Changes

1. Added slither, solidity linter

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
CI not happy ^^
You can run the test class locally in VsCode on PyCharm, it will avoid you to wait for the (long) CI job to know where is the issue

**Comment by leogalbu** [comment]
this is great, thank you very much :)

**Comment by leogalbu** [comment]
@nvuillam I followed your advice and tested locally, replicated the error and fixed it by setting solc in the environmental variables.
Do you have any advice on how to set this on the config file?

**Comment by nvuillam** [comment]
What is solc ?
If you need an env var to be set, you can add that in install descriptor property (dockerfile)

**Comment by leogalbu** [comment]
Solc is the solidity compiler, it is required to use slither, the  static analysis framework.

**Pull request closed without merging**
