### PR TITLE
add KICS

### PR DESCRIPTION
**Pull request by rogeriopeixotocx**
## Proposed Changes

1. add [KICS](kics.io/) IaC scanner 

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
Now you need to solve conflicts before I am able to run CI , sorry ^^

**Comment by nvuillam** [comment]
-you can take all the content of master, it's ok , doc CI job will regenerate KICS doc later anyway

**Comment by rogeriopeixotocx** [comment]
@nvuillam done.. thank you for the directions.

**Comment by rogeriopeixotocx** [comment]
@nvuillam just updated the branch again

**Review by nvuillam — APPROVED** [review]
Nice, thanks for your contribution ! :)
I added a commit to merge conflicts and update cspell, it should be ok now after CI passes

**Pull request merged**
