### PR TITLE
chore: specify docker registry in actions yaml

### PR DESCRIPTION
**Pull request by pratikbalar**
- Specifying docker registry is crucial as my self running this under podman

## Proposed Changes

1. Add `docker.io/.../...` 

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by pratikbalar** [comment]
IDK why build & deploy - DEV CI failed

**Comment by nvuillam** [comment]
@pratikbalar action.yml and dockerfile are generated by build.py , so the update will be a little bit more complex :)

https://github.com/megalinter/megalinter/blob/880b45d4f3659ef9055d6ef749d554feee1549a2/.automation/build.py#L138

**Comment by nvuillam** [comment]
(and about CI if will work after I merge this PR https://github.com/megalinter/megalinter/pull/1118 )

**Comment by pratikbalar** [comment]
> action.yml and dockerfile are generated by build.py , so the update will be a little bit more complex :)

Oh, I will look into that @nvuillam

**Comment by nvuillam** [comment]
I updated your branch :)

But you still need to update build.py then run `bash build.sh` :)

More info -> https://megalinter.github.io/latest/contributing/

**Comment by pratikbalar** [comment]
I think this is not necessary for the time being, so closing this

**Comment by nvuillam** [comment]
@pratikbalar what changed so the update that was critical is now not necessary ?.

**Pull request closed without merging**
