### PR TITLE
quick build to fix stargazers badge regression (see issue #873)

### LINKED ISSUE #873: Stargazers badge outdated
**Describe the bug**
Mega-Linter popularity increased a lot, but stargazers is outdated due to a cache timeout too long

**Expected behavior**
A badge up-to-date (at least in the latest hour)

**Screenshots**

nvuillam_mega-linter

nvuillam github io_mega-linter

**Additional context**
Badge URLs still used legacy name `maxAge`. I suggest to use the new one `cacheSeconds` and limit cache lifetime to 3600 (1 hour)

### PR DESCRIPTION
**Pull request by llaville**
Regression Fixes #873

## Proposed Changes

1. Replace legacy name `maxAge` by `cacheSeconds`
2. Reduce timeout from 2592000 seconds (30 days) to 3600 seconds (1 hour)

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
## [Mega-Linter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/1404055270)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|1.24s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|1.45s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|1.23s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |2.31s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |3.14s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.43s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.88s       |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.2s        |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                         0|2.21s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|9.45s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   20|     |                                                                         0|17.21s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  195|    0|                                                                         0|4.89s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  195|     |                                                                         0|116.48s     |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  195|    0|                                                                         0|4.09s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.63s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  141|     |[**64**](https://github.com/megalinter/megalinter/actions/runs/1404055270)|2.26s       |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  141|    0|                                                                         0|2.8s        |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  141|     |                                                                         0|2.3s        |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  141|    0|                                                                         0|0.48s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  141|     |                                                                         0|62.63s      |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  141|     |                                                                         0|15.79s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  465|     |                                                                         0|36.93s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  312|    0|                                                                         0|0.46s       |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.22s       |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|3.62s       |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|28.07s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.41s       |


See errors details in [**artifact Mega-Linter reports** on GitHub Action page](https://github.com/megalinter/megalinter/actions/runs/1404055270)

**Review by nvuillam — APPROVED** [review]

**Comment by nvuillam** [comment]
It seems internal CI for contributors is broken, i'll have a look ;)

**Comment by llaville** [comment]
@nvuillam You've introduced again a regression https://github.com/megalinter/megalinter/blame/main/mega-linter-runner/README.md#L16 since PR was applied

**Comment by nvuillam** [comment]
Oops... maybe this code is auto-generated ?
I have to succeed to take my way-back plane in Guadeloupe today... so i'll be on my phone only :/

**Pull request merged**
