### PR TITLE
Add fish_indent formatter

### LINKED ISSUE #1039: Add fish shell linter/formatter
The Fish shell has an official formatter, [`fish_indent`](https://fishshell.com/docs/current/cmds/fish_indent.html). Source code can be found at https://github.com/fish-shell/fish-shell/blob/master/src/fish_indent.cpp. 

Could this be added to mega linter?

### PR DESCRIPTION
**Pull request by IlanCosman**
Fixes #1039 

Alright this is how far I've gotten. I'm definitely not confident I did everything right, but hopefully it's a good start 😄

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
Please can you remove flavors part ?
It will be added in "all" MegaLinter image (the main one), but I prefer to not make other flavors heavier :)

**Comment by IlanCosman** [comment]
I understand. Is there a way to make a personal flavor? I.E just what my repository needs, and nothing else? Because I'd prefer not to use the `all` flavor, it's fat 😄

**Comment by nvuillam** [comment]
@IlanCosman > thanks for the updates :)

It depends, what flavor would your project need ?

I'm more and more considering rebuilding flavors for v6, with content more accurate with projects people use ... the current list is build from my experience, but it does not cover everything... there are languages or frameworks in MegaLinter that I never used myself ^^ ( like fish, but also ruby or terraform for example ^^ )

**Comment by IlanCosman** [comment]
My project, https://github.com/IlanCosman/tide, is very simple.
| Descriptor  | Linter                   | Criteria              | Matching files | Format/Fix |
| ----------- | ------------------------ | --------------------- | -------------- | ---------- |
| ACTION      | actionlint               | .yml, .yaml           | 2              | no         |
| COPYPASTE   | jscpd                    |                       | project        | no         |
| CREDENTIALS | secretlint               |                       | project        | no         |
| GIT         | git_diff                 |                       | project        | no         |
| JSON        | jsonlint                 | .json                 | 2              | no         |
| JSON        | eslint-plugin-jsonc      | .json, .json5, .jsonc | 2              | no         |
| JSON        | v8r                      | .json                 | 2              | no         |
| JSON        | prettier                 | .json                 | 2              | no         |
| MARKDOWN    | markdownlint             | .md                   | 9              | no         |
| MARKDOWN    | markdown-link-check      | .md                   | 9              | no         |
| MARKDOWN    | markdown-table-formatter | .md                   | 9              | no         |
| SPELL       | misspell                 |                       | 19             | no         |
| YAML        | prettier                 | .yml, .yaml           | 5              | no         |
| YAML        | yamllint                 | .yml, .yaml           | 5              | no         |
| YAML        | v8r                      | .yml, .yaml           | 5              | no         |

I just have yaml, json, markdown, and fish files.

---

Maybe there could be a helper action that examines that examines what file types you have in your repository and then builds a docker image based on that?

**Comment by nvuillam** [comment]
As documentation flavor already contains BASH, we could assume that adding fish could not hurt, you can make a new commit to do that if you like ;)

If you can add some link to MegaLinter ( can be only a badge ^^) in your README, it will be appreciated :)

**Comment by nvuillam** [comment]
FAILED megalinter/tests/test_megalinter/linters/arm_arm_ttk_test.py::arm_arm_ttk_test::test_success
FAILED megalinter/tests/test_megalinter/linters/fish_fish_indent_test.py::fish_fish_indent_test::test_get_linter_help
FAILED megalinter/tests/test_megalinter/linters/fish_fish_indent_test.py::fish_fish_indent_test::test_success
FAILED megalinter/tests/test_megalinter/linters/json_v8r_test.py::json_v8r_test::test_get_linter_help
FAILED megalinter/tests/test_megalinter/linters/json_v8r_test.py::json_v8r_test::test_get_linter_version
FAILED megalinter/tests/test_megalinter/linters/json_v8r_test.py::json_v8r_test::test_success
FAILED megalinter/tests/test_megalinter/linters/yaml_v8r_test.py::yaml_v8r_test::test_get_linter_help
FAILED megalinter/tests/test_megalinter/linters/yaml_v8r_test.py::yaml_v8r_test::test_get_linter_version
FAILED megalinter/tests/test_megalinter/linters/yaml_v8r_test.py::yaml_v8r_test::test_success

arm and v8r are not your fault (CI is broken due to new versions, fixing PR is in progress)
but fish_indent is on you :p

**Comment by IlanCosman** [comment]
> As documentation flavor already contains BASH, we could assume that adding fish could not hurt, you can make a new commit to do that if you like ;)

What if instead we create a new flavor called `shell`, which is used for shell scripting projects? 
It would be: `bash + fish + most of the documentation linters except for groovy, kotlin, and sql`.
We could expand it with more shell languages in the future, if such linters/formatters are created.

> If you can add some link to MegaLinter ( can be only a badge ^^) in your README, it will be appreciated :)

I'll see what I can do 😄

**Comment by nvuillam** [comment]
@IlanCosman had to add new commits to merge conflicts, let's say what CI says now :)

About shell... do you see a lot of projects where there are different shells used ? ^^

Maybe in the future I could implement a system of votes to define what will be the next flavor :D ( technically we can have 500, but it requires a lot of CI minutes, I don't know the limits of github actions but I wouldn't like to reach them ^^ )

**Comment by IlanCosman** [comment]
CI failed again 😞 I could use some help with these:
```
FAILED fish_fish_indent_test.py::fish_fish_indent_test::test_get_linter_help
FAILED fish_fish_indent_test.py::fish_fish_indent_test::test_get_linter_version
FAILED fish_fish_indent_test.py::fish_fish_indent_test::test_success
```

What are these testing for?

**Comment by nvuillam** [comment]
It just tests that the linter works within MegaLinter :D 

You can manually install the linter on your computer, and run python tests with Test Explorer extension for example

image

**Comment by IlanCosman** [comment]
Alright, I fixed the version test, but I'm going to need help on the other two.

I don't get the help thing at all. `fish_indent --help` works just fine 🤷‍♂️ And most of the descriptor files don't have any instances of "help".

As for the success test, not sure why that should be failing when it worked earlier.

**Comment by nvuillam** [comment]
About the success test failing:

[fish_indent] command: ['fish_indent', '--check', '/tmp/lint/.automation/test/fish_indent/fish_indent_good_1.fish']
[fish_indent] CWD: /
**[fish_indent] result: 1 fish_indent: unrecognized option: check**

**Comment by nvuillam** [comment]
And about help test case

DEBUG    root:Linter.py:738 Linter help command: ['fish_indent', '--help']
DEBUG    root:Linter.py:744 Linter help result: 0 
WARNING  root:Linter.py:752 Unable to get help for linter [fish_indent]
WARNING  root:Linter.py:753 ['fish_indent', '--help'] returned output: (0)

**Comment by nvuillam** [comment]
If there is no --help option, you can define `linter_help_cache` (string) in the descriptor

**Comment by IlanCosman** [comment]
Ah, ok, alpine is installing fish 3.1.2, instead of the newer 3.3.1. Should we update the image?

**Comment by nvuillam** [comment]
You can try but... upgrading pyhton alpine base image version usually breaks other linters... If CI works after update, ok, but I'm afraid you will see other linters breaking (that's what happened last time I tried :/ )

**Comment by IlanCosman** [comment]
Surprisingly, not that many tests failed after upgrading the image:
```
FAILED ansible_ansible_lint_test.py::ansible_ansible_lint_test::test_get_linter_help
FAILED ansible_ansible_lint_test.py::ansible_ansible_lint_test::test_get_linter_version
FAILED ansible_ansible_lint_test.py::ansible_ansible_lint_test::test_success
FAILED fish_fish_indent_test.py::fish_fish_indent_test::test_get_linter_help
FAILED php_phplint_test.py::php_phplint_test::test_get_linter_help
FAILED php_phplint_test.py::php_phplint_test::test_get_linter_version
FAILED php_phplint_test.py::php_phplint_test::test_success
FAILED powershell_powershell_test.py::powershell_powershell_test::test_success
FAILED r_lintr_test.py::r_lintr_test::test_get_linter_help
FAILED r_lintr_test.py::r_lintr_test::test_success
FAILED rst_rstcheck_test.py::rst_rstcheck_test::test_get_linter_help
FAILED rst_rstcheck_test.py::rst_rstcheck_test::test_get_linter_version
FAILED rst_rstcheck_test.py::rst_rstcheck_test::test_success
FAILED rst_rstfmt_test.py::rst_rstfmt_test::test_get_linter_help
FAILED rst_rstfmt_test.py::rst_rstfmt_test::test_get_linter_version
FAILED rst_rstfmt_test.py::rst_rstfmt_test::test_success
```

**Comment by nvuillam** [comment]
Told you :/

Maybe it's better to keep current base image, and try to make work the related fish_indent version ? :)

**Pull request closed without merging**
