### PR TITLE
Use go installer for editorconfig-checker

### PR DESCRIPTION
**Pull request by nvuillam**
Fixes https://github.com/megalinter/megalinter/issues/1282

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/2323616905)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|0.02s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|0.24s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|0.26s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.92s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |3.49s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.26s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.61s       |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.24s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|2.32s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|4.77s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   21|     |                                                                         0|14.84s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  255|    0|                                                                         0|4.74s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  255|     |                                                                         0|4.95s       |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  255|    0|                                                                         0|4.56s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.04s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  150|     |[**64**](https://github.com/megalinter/megalinter/actions/runs/2323616905)|1.84s       |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  150|    0|                                                                         0|2.79s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  150|     |                                                                         0|2.13s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  150|    0|                                                                         0|0.54s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  150|     |                                                                         0|100.71s     |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  150|     |                                                                         0|14.64s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  534|     |                                                                         0|14.06s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  378|    0|                                                                         0|0.55s       |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.01s       |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|2.59s       |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|24.58s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.24s       |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/megalinter/megalinter/actions/runs/2323616905)

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/2324299286)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|0.02s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|0.23s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|0.05s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.77s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |3.51s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.23s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.62s       |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.03s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|1.83s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|4.57s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   21|     |                                                                         0|14.09s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  255|    2|                                                                         0|4.33s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  255|     |                                                                         0|4.16s       |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  255|    2|                                                                         0|3.74s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|0.99s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  150|     |[**64**](https://github.com/megalinter/megalinter/actions/runs/2324299286)|1.79s       |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  150|    0|                                                                         0|2.88s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  150|     |                                                                         0|2.36s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  150|    0|                                                                         0|0.33s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  150|     |                                                                         0|96.82s      |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  150|     |                                                                         0|13.84s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  534|     |                                                                         0|13.37s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  378|    2|                                                                         0|0.3s        |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.01s       |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|2.35s       |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|25.08s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.27s       |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/megalinter/megalinter/actions/runs/2324299286)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [**megalinter/megalinter/flavors/python@v5**](https://megalinter.github.io/flavors/python/) (49 linters)

**Comment by Kurt-von-Laven** [comment]
Cool find. Thanks!

**Comment by Kurt-von-Laven** [comment]
[Looks like it worked!](https://github.com/megalinter/megalinter/pull/1477/files#diff-2f6323e77b7feb0335490317043f3ea11601573f432642c3d1acf80b31ebffb0R21)

**Comment by nvuillam** [comment]
And finally it's not with go but with docker image :)

**Pull request merged**
