### PR TITLE
Add support for Gitpod

### PR DESCRIPTION
**Pull request by ajhalili2006**
## Proposed Changes

1. Adds `.gitpod.yml` to automatically configure Git to set `core.autocrlf` to true and installs extensions from Open VSX that are recommended by the project.
2. Adds a  Python script for synchronization of `.vscode/extensions#recommendations` to `.gitpod.yml#vscode.extensions`

## Roadblockers in adding Gitpod support

* Gitpod Community Forum and Issue Tracker: https://github.com/gitpod-io/gitpod/issues/3356, https://community.gitpod.io/t/workspace-doesnt-start-with-custom-docker-image/3806/5
* Other forks of VS Code:
  * code-server: https://github.com/cdr/code-server/issues/3431 
* Upstream docs: https://code.visualstudio.com/docs/remote/linux#_tips-by-linux-distribution 

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by ajhalili2006** [comment]
For the documentation stuff, maybe it should be on contributing docs, which I'll write soon.

**Comment by ajhalili2006** [comment]
Just rebased against the latest commits from the `main` branch, still working on the custom workspace Dockerfile.

**Comment by ajhalili2006** [comment]
Rebased again against `main`, with the latest commit related to ignoring some Hadolint warnings and errors, particularly pining some package versions in pip, gem, and npm, WORKDIR-related stuff and using `latest` tag for the custom Gitpod workspace image Dockerfile I'm still working on.

**Comment by nvuillam** [comment]
@ajhalili2006 Do you manually write the gitpod Dockerfile ?

If yes, I strongly suggest to automate it, else it will be too long to maintain (all Dockerfiles content are coming from descriptors and generated using build.py

If you want I can manage the automation later, but please at least keep the comments I use for replacements :) (#NPM__START, #NPM__END, PIP__START, PIP__END, etc .... :) )

**Comment by ajhalili2006** [comment]
I tried using the main Dockerfile in an test GitLab repo and it's failed with the following error:

```
cannot ensure Gitpod user exists: [adduser -h /home/gitpod -s /bin/sh -D -G 33333 -u 33333 gitpod]: exit status 1: adduser: unknown group 33333
```

Maybe because its assume that the base image is Debian-based and reproducing some parts of `gitpod/workspace-base`.{^1]

[^1]: https://github.com/gitpod-io/gitpod/issues/3356#issuecomment-963038577

So maybe I'll rewrite the Dockerfile to include only the required Python packages within the repo.

**Comment by ajhalili2006** [comment]
Since I force pushed stuff with lease, old commits can be found at https://github.com/ajhalili2006/mega-linter/tree/old-draft/gitpodify-repo branch.

**Comment by nvuillam** [comment]
Still draft ? :)

**Comment by ajhalili2006** [comment]
Hey @nvuillam, Sorry for the long wait. I'm going to rebase the branch later to ensure its in sync with the main branch.

**Pull request closed without merging**
