### PR TITLE
Don't rely on `DEFAULT_BRANCH` setting.

### LINKED ISSUE #915: Default `DEFAULT_BRANCH` is `master`
**Describe the bug**
[The documentation](https://megalinter.github.io/configuration/#common-variables) was updated at v5 to state that `DEFAULT_BRANCH` defaults to `main`, but it still defaults to `master`.

```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch origin refs/heads/master:refs/remotes/origin/master
  stderr: 'Host key verification failed.
fatal: Could not read from remote repository.
```

**To Reproduce**

1. `cd` into a repository that uses `main` as the default branch.
2. Run Mega-Linter locally at `v5.0.4` with `VALIDATE_ALL_CODEBASE=false` without `DEFAULT_BRANCH` specified.

**Expected behavior**
I expected Mega-Linter Runner to run successfully.

**Additional context**
The documentation itself is also stale: "Warning: In new github repositories, main branch is named `main`, so you need to override this value with `main`."

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
Fixes #915.

Default `DEFAULT_BRANCH` to `HEAD` instead of master.

## Proposed Changes

1. When `DEFAULT_BRANCH` isn't specified, diff against `origin/HEAD` to determine which files to lint in incremental mode. As before, fetch the precise ref we require if it isn't present locally. This is a breaking change for users who don't specify `DEFAULT_BRANCH` and have `origin/HEAD` misconfigured.
2. Deprecate `DEFAULT_BRANCH` since it is only kept for backwards compatibility.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
## [Mega-Linter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/1434095475)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|1.12s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|1.44s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|1.24s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |2.41s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |2.88s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.43s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.91s       |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.21s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                         0|2.33s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|9.32s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   20|     |                                                                         0|16.34s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  196|    0|                                                                         0|5.06s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  196|     |                                                                         0|113.3s      |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  196|    0|                                                                         0|4.0s        |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.4s        |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  142|     |[**64**](https://github.com/megalinter/megalinter/actions/runs/1434095475)|2.06s       |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  142|    0|                                                                         0|2.58s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  142|     |                                                                         0|1.99s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  142|    0|                                                                         0|0.5s        |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  142|     |                                                                         0|60.12s      |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  142|     |                                                                         0|15.29s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  467|     |                                                                         0|36.42s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  313|    0|                                                                         0|0.42s       |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.21s       |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|3.54s       |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|27.34s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.27s       |


See errors details in [**artifact Mega-Linter reports** on GitHub Action page](https://github.com/megalinter/megalinter/actions/runs/1434095475)

**Comment by Kurt-von-Laven** [comment]
I am guessing we pulled in a new version of bandit that is complaining about 64 pre-existing issues.

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/1457576526)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|0.69s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|0.93s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|0.71s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |2.34s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |3.14s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.34s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.8s        |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.11s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                         0|2.12s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|7.81s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   20|     |                                                                         0|14.78s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  196|    0|                                                                         0|4.93s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  196|     |                                                                         0|99.71s      |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  196|    0|                                                                         0|4.55s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.5s        |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  142|     |[**64**](https://github.com/megalinter/megalinter/actions/runs/1457576526)|2.22s       |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  142|    0|                                                                         0|2.75s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  142|     |                                                                         0|2.18s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  142|    0|                                                                         0|0.44s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  142|     |                                                                         0|63.32s      |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  142|     |                                                                         0|16.13s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  466|     |                                                                         0|38.14s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  312|    0|                                                                         0|0.36s       |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.12s       |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|3.85s       |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|25.68s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.34s       |


See errors details in [**artifact MegaLinter reports** on GitHub Action page](https://github.com/megalinter/megalinter/actions/runs/1457576526)

**Comment by Kurt-von-Laven** [comment]
@nvuillam, I scrolled through the bandit issues, and they are all pre-existing. I incorporated your feedback regarding honoring `DEFAULT_BRANCH`.

**Comment by Kurt-von-Laven** [comment]
I'm a bit confused about our CI and having trouble figuring out how to rerun the check that still appears hung. Superficially, it seems like there is some redundancy between the push and pull request versions of several workflows that could be eliminated by consolidating them into single workflows with multiple event triggers?

**Comment by nvuillam** [comment]
There was a branch protection rule on job "Mega-Linter", and as a renamed every Mega-Linter into MegaLinter recently... :)

Solved :)

image

**Comment by nvuillam** [comment]
I'm not sure about this PR... seems to be a too impacting change, maybe we can keep using DEFAULT_BRANCH, but in case the one defined does not exists, check if "main" or "master" exists, and use it ?

**Comment by Kurt-von-Laven** [comment]
Before I get off in the weeds discussing the more esoteric edge cases here, is it already clear that the present iteration continues to honor `DEFAULT_BRANCH` when it's specified?

**Comment by Kurt-von-Laven** [comment]
@nvuillam, the present iteration is already very similar to what you have suggested, but uses the default branch configured on GitHub (a.k.a., `origin/HEAD`) rather hard-coding a list of possible default branch names to consider in an arbitrary priority order.

**Comment by nvuillam** [comment]
I think that if DEFAULT_BRANCH is specified, the behavior should remain the same than today, but when it is not defined , your updates sounds good, is your PR corresponding to such behaviour ?

**Comment by Kurt-von-Laven** [comment]
Yep, that is what is implemented.

**Comment by nvuillam** [comment]
new default branch is "HEAD"which is not the name of a branch... i'm afraid it's a breaking change, i don't feel really confident about it :/

**Comment by Kurt-von-Laven** [comment]
`HEAD` is a symbolic ref for the head commit on the default branch. I have tested it and am confident that it does what I expect. As the commit message details, there is one edge case that it currently handles poorly. Git currently doesn't update which branch `origin/HEAD` points to automatically if it changes, so the user has to either run `git remote set-head origin -a` to update their existing clone or re-clone when the default branch is changed on the remote. That case doesn't apply in CI, where every clone is typically fresh, and obviously it doesn't apply to anyone who has set their `DEFAULT_BRANCH` for MegaLinter. Since we currently default to master, the only scenario where the user would now have to take an action but didn't previously is when they run MegaLinter locally in a repo they cloned before its default branch was changed from something other than `master` to `master`, they haven't updated `origin/HEAD`, and they don't specify `DEFAULT_BRANCH`. For context, users running locally aren't going to be getting any refs fetched for them automatically right now, because we don't have a way to access their SSH keys.

**Comment by Kurt-von-Laven** [comment]
Here are some workflow runs showing that this doesn't break the use of MegaLinter in CI...

with `VALIDATE_ALL_CODEBASE=false` and `fetch-depth: 1` (only clone most recent commit):
- https://github.com/megalinter/megalinter/actions/runs/1505886950
- https://github.com/megalinter/megalinter/actions/runs/1505886951
- https://github.com/megalinter/megalinter/actions/runs/1505886952
- https://github.com/megalinter/megalinter/actions/runs/1505886953
- https://github.com/megalinter/megalinter/actions/runs/1505887009
- https://github.com/megalinter/megalinter/actions/runs/1505887011
- https://github.com/megalinter/megalinter/actions/runs/1505887015

with `VALIDATE_ALL_CODEBASE=false` and `fetch-depth: 0` (clone full history):
- https://github.com/megalinter/megalinter/actions/runs/1506033831
- https://github.com/megalinter/megalinter/actions/runs/1506033832
- https://github.com/megalinter/megalinter/actions/runs/1506033833
- https://github.com/megalinter/megalinter/actions/runs/1506033834
- https://github.com/megalinter/megalinter/actions/runs/1506033919
- https://github.com/megalinter/megalinter/actions/runs/1506033921
- https://github.com/megalinter/megalinter/actions/runs/1506033925

On the ones with a "MegaLinter" step, you can see the list of modified files computed by `git diff` near the top of the output.

**Review by nvuillam — APPROVED** [review]
I still have some doubts, but mostly because I'm not a git expert... so if my co-maintainer is sure, I should trust him ;)

**Comment by Kurt-von-Laven** [comment]
You can run `git fetch origin HEAD:refs/remotes/origin/HEAD` or `git fetch origin refs/heads/{branch}:refs/remotes/origin/{branch}` if you are curious to see the effect for yourself, but we only run this when `origin/HEAD` isn't available locally to avoid breaking local use of MegaLinter. The fetch command updates the local ref (e.g., `origin/HEAD` on your laptop) after the colon from the remote ref before the colon (e.g., `HEAD` on GitHub). `origin` in most cases means the remote that is on GitHub or similar.

**Comment by nvuillam** [comment]
Nice explanation :)

**Pull request merged**
