### PR TITLE
Upgrade ktlint to 0.42.1

### LINKED ISSUE #878: Upgrade ktlint (0.40.0 ➜ 0.42.1)
**Describe the bug**
The Kotlin linter [ktlint](https://github.com/pinterest/ktlint/releases/) is outdated. A few substantial [rules were added](https://github.com/pinterest/ktlint/blob/master/CHANGELOG.md) since the 0.40.0 release.

**To Reproduce**

1. See generated [linter-versions.json](https://github.com/nvuillam/mega-linter/blob/master/.automation/generated/linter-versions.json#L34).

**Expected behavior**
The [latest stable release](https://github.com/pinterest/ktlint/releases/) of `klint` is available with Mega-Linter.

**Additional context**
I'd be ready contribute the upgrade via a PR. Can you advise which file(s) to update [before running `bash build.sh`](https://nvuillam.github.io/mega-linter/contributing/#with-write-access) for this change?

### PR DESCRIPTION
**Pull request by lars-reimann**
Fixes #878 **(or leave this issue open for #976, maybe with another title?)**

## Proposed Changes

1. Upgrade ktlint to 0.42.1

I've tested this version locally with JDK 1.8 without issues. Let's see how it goes here. The auto-upgrade from #976 would be a more desirable solution but this is a temporary fix.

### Author/Contributor
- [X] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by lars-reimann** [comment]
The failing test is `megalinter/tests/test_megalinter/plugins_test.py::plugins_test::test_load_plugin_success`, which failed with a timeout after 60 seconds when running the command `npm install jsonlint -g && echo "This is my te..`. It's probably not caused by the change in this PR.

**Comment by nvuillam** [comment]
Plugins contain nothing, that's very strange ^^
I launched again ci jobs

**Comment by nvuillam** [comment]
And about mega linter it's my fault... i forced a PR just before taking a plane... i'm kind of ashamed, i'll correct that asap ^^

**Comment by lars-reimann** [comment]
No worries, hope you had a good flight.

**Comment by nvuillam** [comment]
I did 😎

**Comment by nvuillam** [comment]
Great !!:)

**Comment by nvuillam** [comment]
@lars-reimann please can you run `bash build.sh`  ? it will update the dockerfiles

**Comment by lars-reimann** [comment]
Dropping this in favor of #976, since version 0.42.1 [does not support absolute paths](https://github.com/pinterest/ktlint/pull/1199).

**Pull request closed without merging**
