### PR TITLE
Update .cspell default config

### PR DESCRIPTION
**Pull request by nvuillam**
Fixes https://github.com/megalinter/megalinter/issues/1220

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/1769771121)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|0.03s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|0.23s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|0.23s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.85s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |3.17s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.23s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.8s        |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.22s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|2.09s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|4.55s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   21|     |                                                                         0|13.59s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  251|    0|                                                                         0|4.74s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  251|     |                                                                         0|63.61s      |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  251|    0|                                                                         0|4.29s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.12s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  147|     |[**64**](https://github.com/megalinter/megalinter/actions/runs/1769771121)|2.14s       |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  147|    0|                                                                         0|2.74s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  147|     |                                                                         0|1.99s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  147|    0|                                                                         0|0.52s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  147|     |                                                                         0|78.2s       |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  147|     |                                                                         0|19.13s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  527|     |                                                                         0|24.91s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  372|    0|                                                                         0|0.53s       |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.0s        |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|3.26s       |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|21.61s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.27s       |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/megalinter/megalinter/actions/runs/1769771121)

**Comment by Jason3S** [comment]
@nvuillam,

How does the MegaLinter control the command line parameters? I didn't find the actual call anywhere in the code.  For example, using `--file-list` would be much better than 100's of files listed on the command line for PRs diffs.

**Comment by nvuillam** [comment]
@Jason3S linter commands are automatically generated using descriptors :)

The one for cspell is here -> https://github.com/megalinter/megalinter/blob/ac0c04510828d30907ed67eefdc1b5754e106437/megalinter/descriptors/spell.megalinter-descriptor.yml#L41

So basically, it does something like `cspell -c .cspell.json file1 file2 file3 file4 ...`

Do you mean it would work better with `cspell -c .cspell.json --file-list file1 file2 file3 file4 ...`  ?

**Comment by Jason3S** [comment]
@nvuillam,

That is still on the command line.

How are you populating the command line? A long list of files won't fit on the command line. Or do you break it up into shorter lists of files?

Are you doing something like? `git diff origin/main...pr-branch --name-only`

For example, the following will work:

```sh
git diff origin/main...pr-branch --name-only | cspell -c .cspell.json --file-list stdin
```

Which means read the file list from `stdin`.

Or if it is in an environment variable:

```sh
echo "$FILE_LIST" | cspell -c .cspell.json --file-list stdin
```

**Comment by nvuillam** [comment]
@Jason3S I have working linters with very long list of files in command line , why wouldn't it work with cspell ?

**Comment by Jason3S** [comment]
I guess it depends upon the system: [Accept files list from stdin · Issue #1850 · streetsidesoftware/cspell](https://github.com/streetsidesoftware/cspell/issues/1850)

I have also hit the command line limit with large PRs on a mono-repo.

**Comment by Jason3S** [comment]
In any case, if it is working for most of your implementations, then it isn't a problem.

**Comment by nvuillam** [comment]
I can use your way with echo by overriding default way to build command line, but i try to avoid such overrides because it generates more maintenance ^^
So i'll probably wait for the first case where the limit is reached ^^

Meanwhile, do you confirm that it's better to have --file-list with the list of files after than without --file-list ?

**Comment by Jason3S** [comment]
Use the current way: `cspell file1 file2 file3 ...`

`--file-list` means you are giving it a file that has the list of files to check. For example:

- `changed-files.txt` - contains a list of all the files that need to be checked.
- `cspell --file-list changed-files.txt` - would read the contents of `changed-files.txt` and use it as the list of files.

**Pull request merged**
