### PR TITLE
Bump Python 3.9.7 Alpine

### LINKED ISSUE #1406: Vulnerabilities in python:3.9.7-alpine3.13 base image
Hey all, loving the tool. Just wanted to bring some security vulnerabilities snyk.io found in the python:3.9.7-alpine3.13 base image.

There are 8 vulnerabilities listed as `critical` coming from the `expat` package in the alpine:3.13 image.

https://snyk.io/vuln/alpine%3A3.13%3Aexpat

Critical Vulnerabilities Found

- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2342171
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2342172
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2342173
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2406625
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2406626
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2407739
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2407752
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2407757

This was found on the python flavor, but I believe this applies to all flavors.

### PR DESCRIPTION
**Pull request by a1flecke**
Fixes #1406 

## Proposed Changes

1. python:3.9.7-alpine3.13 --> python:3.9.7-alpine3.14
### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by Kurt-von-Laven — CHANGES_REQUESTED** [review]
The same base image is used by all of the flavors, so those should be bumped as well.

**Comment by nvuillam** [comment]
@a1flecke you need to run `bash build.sh` , please see [contributing instructions](https://megalinter.github.io/latest/contributing/) :)

**Comment by a1flecke** [comment]
> @a1flecke you need to run `bash build.sh` , please see [contributing instructions](https://megalinter.github.io/latest/contributing/) :)

@nvuillam I am on a M1.  Any guidance on this as it appears many of megalinters dependencies do not have aarch64 support, at least when I tried going through the dev container route.  I could script around the chromium issue but then I ran into dotenv-linter just flat out not releasing a aarch64 alpine binary.

If push comes to shove I might be able to find an old intel macbook pro.  My goal here is just to bump alpine and eliminate the critical vulnerabilities so I can use megalinter.

**Comment by nvuillam** [comment]
@a1flecke you don't need to build docker image :)
Just running python code that will propagate the base docker image name to flavors images will do the job ;)

**Comment by nvuillam** [comment]
But you allowed maintainers to commit in your repo, so as it took 1mn I did it myself and pushed the new commit ^^

**Comment by Kurt-von-Laven** [comment]
pip is unable to find a version of snakemake that is compatible with the other dependencies. It keeps trying older and older versions until it eventually reaches 5.27.2, a bad release that cannot be set up. The issue may be reproduced locally by running `pip install ansible-lint cfn-lint snakemake` (or `pip install ansible-lint cfn-lint`). The breakage is unrelated to this pull request. It was caused by [ansible/ansible-lint#2035](https://github.com/ansible/ansible-lint/pull/2035/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R35), which added a dependency on `jsonschema==4.5.1`, whereas [cfn-lint requires `jsonschema~=3.0`](https://github.com/aws-cloudformation/cfn-lint/blob/c381e5f9d0611d4959c317426dbbe248252a58f5/setup.py#L48). One short-term approach might be for us to pin `ansible-lint==6.0.2`. Longer term, it might be better to use [Poetry](https://python-poetry.org/) than pip since it would allow us to lock the transitive closure of our dependencies and automatically explain any conflicts caused by upgrades to us.

**Comment by a1flecke** [comment]
@Kurt-von-Laven 

> Longer term, it might be better to use [Poetry](https://python-poetry.org/) than pip since it would allow us to lock the transitive closure of our dependencies and automatically explain any conflicts caused by upgrades to us.

We ended up switching from pipenv to poetry for our projects for a different lockfile reason.  Poetry's lockfiles included hashes for all architectures which helps in our mixed-architecture (arm, amd) development teams.

Thanks for the feedback and quick replies.  I will wait for the build to be fixed.

**Comment by Kurt-von-Laven** [comment]
@a1flecke, I believe the build has been fixed, so hopefully you will get green lights after rebasing and force-pushing.

**Comment by nvuillam** [comment]
I don't understand, the idealTree npm issue was supposed to be solved thanks to WORKDIR instruction :/

**Comment by nvuillam** [comment]
npm version installed for this alpine version is... the same than node.js , i wonder if there is not an issue ... maybe that upgrading to a later version would do the job :/

**Comment by nvuillam** [comment]
@Kurt-von-Laven v6 is based on python:3.10.4-alpine3.15 :)

**Pull request closed without merging**
