### PR TITLE
Fix get linter version when linter is a npm plugin like an eslint plugin

### LINKED ISSUE #773: [v4.46] EditorConfigChecker perf and config file issues
**Describe the bug**
Default config file TEMPLATE does not exists, and custom file contents not accepted that follows to a perf issue !

TEMPLATE missing in https://github.com/nvuillam/mega-linter/tree/v4.46.0/TEMPLATES, while default specified in [descriptor](https://github.com/nvuillam/mega-linter/blob/v4.46.0/megalinter/descriptors/editorconfig.megalinter-descriptor.yml#L19-L20)
 is `.ecrc` 

**To Reproduce**
Steps to reproduce the behavior, when a custom config file is provided:

1. Have a repository with lot of files and of course an `.editorconfig` file required by [rule](https://github.com/nvuillam/mega-linter/blob/v4.46.0/megalinter/descriptors/editorconfig.megalinter-descriptor.yml#L7-L8)
2. Add a `.mega-linter.yml` config file with at least an `EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE` key/value (i.e:  `EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: "(\\.idea|\\.editorconfig|\\.github|\\.box\\.metadata\\.cache|LICENSE)"`)
3. Add a custom editorconfig-checker config file `.ecrc` with following contents 
<details><summary>.github/linters/.ecrc</summary>

```
{
  "Version": "2.3.5",
  "Verbose": false,
  "Debug": false,
  "IgnoreDefaults": false,
  "SpacesAftertabs": false,
  "NoColor": false,
  "Exclude": [],
  "AllowedContentTypes": [],
  "PassedFiles": [
    ".github/ISSUE_TEMPLATE/bug_report.md",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/linters/.ecrc"
    "LICENSE"
  ],
  "Disable": {
    "EndOfLine": false,
    "Indentation": false,
    "InsertFinalNewline": false,
    "TrimTrailingWhitespace": false,
    "IndentSize": false,
    "MaxLineLength": false
  }
}
```

</details> 
4. Run locally on source code with command  `docker run -v $(pwd):/tmp/lint nvuillam/mega-linter-php:v4`

**Expected behavior**
Only files declared by `PassedFiles` key should be analysed. Currently all files are analysed 

**Screenshots**

```
[config] /tmp/lint/.mega-linter.yml + Environment variables
----------------------------------------------------------------------------------------------------
------------------------------------------- Mega-Linter --------------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2021-09-21T20:48:53Z
 - Image Revision: 96137434
 - Image Version: v4
----------------------------------------------------------------------------------------------------
The Mega-Linter documentation can be found at:
 - https://nvuillam.github.io/mega-linter
----------------------------------------------------------------------------------------------------
GITHUB_REPOSITORY:
GITHUB_REF:
GITHUB_RUN_ID:


Skipped linters: ANSIBLE_ANSIBLE_LINT, ARM_ARM_TTK, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, CLOJURE_CLJ_KONDO, CLOUDFORMATION_CFN_LINT, COFFEE_COFFEELINT, COPYPASTE_JSCPD, CPP_CPPLINT, CREDENTIALS_SECRETLINT, CSHARP_DOTNET_FORMAT, CSS_SCSS_LINT, CSS_STYLELINT, C_CPPLINT, DART_DARTANALYZER, DOCKERFILE_DOCKERFILELINT, DOCKERFILE_HADOLINT, ENV_DOTENV_LINTER, GHERKIN_GHERKIN_LINT, GIT_GIT_DIFF, GO_GOLANGCI_LINT, GO_REVIVE, GRAPHQL_GRAPHQL_SCHEMA_LINTER, GROOVY_NPM_GROOVY_LINT, HTML_HTMLHINT, JAVASCRIPT_ES, JAVASCRIPT_PRETTIER, JAVASCRIPT_STANDARD, JAVA_CHECKSTYLE, JSON_ESLINT_PLUGIN_JSONC, JSON_JSONLINT, JSON_PRETTIER, JSON_V8R, JSX_ESLINT, KOTLIN_KTLINT, KUBERNETES_KUBEVAL, LATEX_CHKTEX, LUA_LUACHECK, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, MARKDOWN_REMARK_LINT, OPENAPI_SPECTRAL, PERL_PERLCRITIC, PHP_BUILTIN, PHP_PHPCS, PHP_PHPSTAN, PHP_PSALM, POWERSHELL_POWERSHELL, PROTOBUF_PROTOLINT, PUPPET_PUPPET_LINT, PYTHON_BANDIT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_MYPY, PYTHON_PYLINT, RAKU_RAKU, RST_RSTCHECK, RST_RSTFMT, RST_RST_LINT, RUBY_RUBOCOP, RUST_CLIPPY, R_LINTR, SALESFORCE_SFDX_SCANNER_APEX, SALESFORCE_SFDX_SCANNER_AURA, SALESFORCE_SFDX_SCANNER_LWC, SCALA_SCALAFIX, SNAKEMAKE_LINT, SNAKEMAKE_SNAKEFMT, SPELL_CSPELL, SPELL_MISSPELL, SQL_SQLFLUFF, SQL_SQL_LINT, SQL_TSQLLINT, SWIFT_SWIFTLINT, TEKTON_TEKTON_LINT, TERRAFORM_CHECKOV, TERRAFORM_TERRAFORM_FMT, TERRAFORM_TERRAGRUNT, TERRAFORM_TERRASCAN, TERRAFORM_TFLINT, TSX_ESLINT, TYPESCRIPT_ES, TYPESCRIPT_PRETTIER, TYPESCRIPT_STANDARD, VBDOTNET_DOTNET_FORMAT, XML_XMLLINT, YAML_PRETTIER, YAML_V8R, YAML_YAMLLINT
To receive reports as email, please set variable EMAIL_REPORTER_EMAIL
Listing all files in directory [/tmp/lint], then filter with:
- File extensions: *
- Excluding regex: (vendor/)
Kept [1790] files on [4092] found files

+----MATCHING LINTERS-----------------+----------+----------------+------------+
| Descriptor   | Linter               | Criteria | Matching files | Format/Fix |
+--------------+----------------------+----------+----------------+------------+
| EDITORCONFIG | editorconfig-checker | *        | 1773           | no         |
+--------------+----------------------+----------+----------------+------------+


### Processed [EDITORCONFIG] files
- Using [editorconfig-checker v2.3.5] https://editorconfig-checker.github.io/
- Mega-Linter key: [EDITORCONFIG_EDITORCONFIG_CHECKER]
- Rules config: [/.github/linters/.ecrc]

```

**Additional context**
When I run the [docker](https://github.com/editorconfig-checker/editorconfig-checker#docker) image of editorconfig-checker it's really fast because only files asked are analysed. 

```
time docker run -it --rm --volume=$PWD:/check mstruebing/editorconfig-checker ec -config .github/linters/.ecrc
.ecrc~:
        Wrong line endings or new final newline
        2: Wrong amount of left-padding spaces(want multiple of 4)
        3: Wrong amount of left-padding spaces(want multiple of 4)
        4: Wrong amount of left-padding spaces(want multiple of 4)
        5: Wrong amount of left-padding spaces(want multiple of 4)
        6: Wrong amount of left-padding spaces(want multiple of 4)
        7: Wrong amount of left-padding spaces(want multiple of 4)
        8: Wrong amount of left-padding spaces(want multiple of 4)
        9: Wrong amount of left-padding spaces(want multiple of 4)
        10: Wrong amount of left-padding spaces(want multiple of 4)
        11: Wrong amount of left-padding spaces(want multiple of 4)
        18: Wrong amount of left-padding spaces(want multiple of 4)
.github/linters/.ecrc:
        2: Wrong amount of left-padding spaces(want multiple of 4)
        3: Wrong amount of left-padding spaces(want multiple of 4)
        4: Wrong amount of left-padding spaces(want multiple of 4)
        5: Wrong amount of left-padding spaces(want multiple of 4)
        6: Wrong amount of left-padding spaces(want multiple of 4)
        7: Wrong amount of left-padding spaces(want multiple of 4)
        8: Wrong amount of left-padding spaces(want multiple of 4)
        9: Wrong amount of left-padding spaces(want multiple of 4)
        10: Wrong amount of left-padding spaces(want multiple of 4)
        15: Wrong amount of left-padding spaces(want multiple of 4)
        16: Wrong amount of left-padding spaces(want multiple of 4)
        23: Wrong amount of left-padding spaces(want multiple of 4)
.github/ISSUE_TEMPLATE/config.yml:
        3: Wrong amount of left-padding spaces(want multiple of 4)
.github/workflows/php-tests.yaml:
        35: Wrong amount of left-padding spaces(want multiple of 4)
LICENSE:
        8: Wrong amount of left-padding spaces(want multiple of 4)
        11: Wrong amount of left-padding spaces(want multiple of 4)
        12: Wrong amount of left-padding spaces(want multiple of 4)
        15: Wrong amount of left-padding spaces(want multiple of 4)
        16: Wrong amount of left-padding spaces(want multiple of 4)

31 errors found

real    0m2.885s
user    0m0.091s
sys     0m0.045s
```

### PR DESCRIPTION
**Pull request by nvuillam**
Fixes #773

### CODE REVIEW

**Comment by nvuillam** [comment]
## [Mega-Linter](https://nvuillam.github.io/mega-linter) status: :warning: [**WARNING**](https://github.com/nvuillam/mega-linter/actions/runs/1301474691)

|   Descriptor   |                                                     Linter                                                     |Files|Fixed|                                 Errors                                  |Elapsed time|
|----------------|----------------------------------------------------------------------------------------------------------------|-----|----:|-------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://nvuillam.github.io/mega-linter/descriptors/bash_bash_exec)                                  |    6|     |                                                                        0|1.38s       |
|✅ BASH         |[shellcheck](https://nvuillam.github.io/mega-linter/descriptors/bash_shellcheck)                                |    6|     |                                                                        0|1.61s       |
|✅ BASH         |[shfmt](https://nvuillam.github.io/mega-linter/descriptors/bash_shfmt)                                          |    6|    0|                                                                        0|1.34s       |
|✅ COPYPASTE    |[jscpd](https://nvuillam.github.io/mega-linter/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                       |2.81s       |
|✅ CREDENTIALS  |[secretlint](https://nvuillam.github.io/mega-linter/descriptors/credentials_secretlint)                         |yes  |     |no                                                                       |3.25s       |
|✅ CSS          |[stylelint](https://nvuillam.github.io/mega-linter/descriptors/css_stylelint)                                   |    1|    0|                                                                        0|1.37s       |
|✅ DOCKERFILE   |[dockerfilelint](https://nvuillam.github.io/mega-linter/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                        0|0.48s       |
|✅ DOCKERFILE   |[hadolint](https://nvuillam.github.io/mega-linter/descriptors/dockerfile_hadolint)                              |    1|     |                                                                        0|1.15s       |
|✅ GIT          |[git_diff](https://nvuillam.github.io/mega-linter/descriptors/git_git_diff)                                     |yes  |     |no                                                                       |0.23s       |
|✅ JSON         |[eslint-plugin-jsonc](https://nvuillam.github.io/mega-linter/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                        0|2.56s       |
|✅ JSON         |[jsonlint](https://nvuillam.github.io/mega-linter/descriptors/json_jsonlint)                                    |   19|     |                                                                        0|11.33s      |
|✅ JSON         |[v8r](https://nvuillam.github.io/mega-linter/descriptors/json_v8r)                                              |   20|     |                                                                        0|18.53s      |
|✅ MARKDOWN     |[markdownlint](https://nvuillam.github.io/mega-linter/descriptors/markdown_markdownlint)                        |  193|    2|                                                                        0|5.31s       |
|✅ MARKDOWN     |[markdown-link-check](https://nvuillam.github.io/mega-linter/descriptors/markdown_markdown_link_check)          |  193|     |                                                                        0|135.48s     |
|✅ MARKDOWN     |[markdown-table-formatter](https://nvuillam.github.io/mega-linter/descriptors/markdown_markdown_table_formatter)|  193|    2|                                                                        0|4.83s       |
|✅ OPENAPI      |[spectral](https://nvuillam.github.io/mega-linter/descriptors/openapi_spectral)                                 |    1|     |                                                                        0|1.65s       |
|:warning: PYTHON|[bandit](https://nvuillam.github.io/mega-linter/descriptors/python_bandit)                                      |  139|     |[**64**](https://github.com/nvuillam/mega-linter/actions/runs/1301474691)|2.6s        |
|✅ PYTHON       |[black](https://nvuillam.github.io/mega-linter/descriptors/python_black)                                        |  139|    1|                                                                        0|3.84s       |
|✅ PYTHON       |[flake8](https://nvuillam.github.io/mega-linter/descriptors/python_flake8)                                      |  139|     |                                                                        0|2.62s       |
|✅ PYTHON       |[isort](https://nvuillam.github.io/mega-linter/descriptors/python_isort)                                        |  139|    1|                                                                        0|0.57s       |
|✅ PYTHON       |[mypy](https://nvuillam.github.io/mega-linter/descriptors/python_mypy)                                          |  139|     |                                                                        0|79.72s      |
|✅ PYTHON       |[pylint](https://nvuillam.github.io/mega-linter/descriptors/python_pylint)                                      |  139|     |                                                                        0|18.76s      |
|✅ SPELL        |[cspell](https://nvuillam.github.io/mega-linter/descriptors/spell_cspell)                                       |  474|     |                                                                        0|42.52s      |
|✅ SPELL        |[misspell](https://nvuillam.github.io/mega-linter/descriptors/spell_misspell)                                   |  323|    3|                                                                        0|0.48s       |
|✅ XML          |[xmllint](https://nvuillam.github.io/mega-linter/descriptors/xml_xmllint)                                       |    2|     |                                                                        0|0.24s       |
|✅ YAML         |[prettier](https://nvuillam.github.io/mega-linter/descriptors/yaml_prettier)                                    |   89|    0|                                                                        0|4.85s       |
|✅ YAML         |[v8r](https://nvuillam.github.io/mega-linter/descriptors/yaml_v8r)                                              |   33|     |                                                                        0|46.19s      |
|✅ YAML         |[yamllint](https://nvuillam.github.io/mega-linter/descriptors/yaml_yamllint)                                    |   90|     |                                                                        0|1.87s       |


See errors details in [**artifact Mega-Linter reports** on GitHub Action page](https://github.com/nvuillam/mega-linter/actions/runs/1301474691)

**Comment by Kurt-von-Laven** [comment]
The issue this pull request addresses was decomposed into #845.

**Comment by Kurt-von-Laven** [comment]
@nvuillam, is this PR mostly working or genuinely stale?

**Comment by nvuillam** [comment]
@Kurt-von-Laven this PR seems good, I just forgot to validate it ^^

**Comment by nvuillam** [comment]
Plz can you merge conflicts with changelog ? 👼

**Comment by Kurt-von-Laven** [comment]
Rebased! I also shortened the commit message to 50 characters or less to avoid it getting truncated by GitHub (or VSCode getting angry with me ha ha).

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/1532844953)

|   Descriptor   |                                                  Linter                                                   |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|-----------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/beta/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|1.26s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/beta/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|1.5s        |
|✅ BASH         |[shfmt](https://megalinter.github.io/beta/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|1.3s        |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.97s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/beta/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |3.0s        |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/beta/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.42s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/beta/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.97s       |
|✅ GIT          |[git_diff](https://megalinter.github.io/beta/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.21s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/beta/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                         0|2.67s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|8.68s       |
|✅ JSON         |[v8r](https://megalinter.github.io/beta/descriptors/json_v8r)                                              |   20|     |                                                                         0|15.23s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/beta/descriptors/markdown_markdownlint)                        |  197|    0|                                                                         0|4.5s        |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/beta/descriptors/markdown_markdown_link_check)          |  197|     |                                                                         0|84.16s      |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/beta/descriptors/markdown_markdown_table_formatter)|  197|    0|                                                                         0|4.41s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.35s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/beta/descriptors/python_bandit)                                      |  143|     |[**64**](https://github.com/megalinter/megalinter/actions/runs/1532844953)|2.38s       |
|✅ PYTHON       |[black](https://megalinter.github.io/beta/descriptors/python_black)                                        |  143|    0|                                                                         0|2.84s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/beta/descriptors/python_flake8)                                      |  143|     |                                                                         0|2.38s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/beta/descriptors/python_isort)                                        |  143|    0|                                                                         0|0.51s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/beta/descriptors/python_mypy)                                          |  143|     |                                                                         0|65.33s      |
|✅ PYTHON       |[pylint](https://megalinter.github.io/beta/descriptors/python_pylint)                                      |  143|     |                                                                         0|18.12s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/beta/descriptors/spell_cspell)                                       |  468|     |                                                                         0|27.43s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/beta/descriptors/spell_misspell)                                   |  313|    0|                                                                         0|0.43s       |
|✅ XML          |[xmllint](https://megalinter.github.io/beta/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.21s       |
|✅ YAML         |[prettier](https://megalinter.github.io/beta/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|3.13s       |
|✅ YAML         |[v8r](https://megalinter.github.io/beta/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|23.09s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/beta/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.46s       |


See errors details in [**artifact MegaLinter reports** on GitHub Action page](https://github.com/megalinter/megalinter/actions/runs/1532844953)

**Comment by nvuillam** [comment]
cross fingers ^^

**Review by Kurt-von-Laven — APPROVED** [review]
**LGTM** (Looks Good To Me)

**Pull request merged**
